import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Map from '../components/map';


const inter = Inter({ subsets: ['latin'] });

export default function Home(): JSX.Element {
    return (
        <>
            <Head>
                <title>Runoff Risk Predictor</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <Map lattitude={39.6837} longitude={-75.7497} zoom={7}/>
                </div>
            </main>
        </>
    );
}
