import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Map from '@/components/map';
import { useState } from 'react';
import { Grid } from '@chakra-ui/react';
import {
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
} from '@chakra-ui/react';
import Slidebar from '@/components/slidebar';

const inter = Inter({ subsets: ['latin'] });

export default function Home(): JSX.Element {
    const [day, setDay] = useState<number>(0);
    return (
        <>
            <Head>
                <title>Runoff Risk Predictor</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Grid templateColumns='repeat(2, 1fr)' gap={0} height="100vh">
                    <Map latitude={43.1031} longitude={-84.7497} zoom={5} day={day} setDay={setDay} />
                    <div>
                        <div className={styles.header}>University of Delaware Runoff Risk Predictor</div>
                        <TableContainer>
                            <Table variant='simple'>
                                <TableCaption>Slide the bar to select a day. Predictions are generated daily.</TableCaption>
                                <Thead>
                                    <Tr>
                                        <Th>Date</Th>
                                        <Th>Runoff Risk</Th>
                                        <Th>Rainfall</Th>
                                        <Th>Snowmelt</Th>
                                    </Tr>
                                </Thead>
                                <Tbody>
                                    {[...Array(10).keys()].map((x) =>(
                                        <Tr key={x}>
                                            <Td>04/23/22</Td>
                                            <Td>High</Td>
                                            <Td>2 millimetres (mm)</Td>
                                            <Td>5 millimetres (mm)</Td>
                                        </Tr>
                                    ))}
                                </Tbody>
                            </Table>
                        </TableContainer>
                        <Slidebar day={day} setDay={setDay}/>
                    </div>
                </Grid>
            </main>
        </>
    );
}
