import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Map from '@/components/map';

const inter = Inter({ subsets: ['latin'] });
export default function Home(): JSX.Element {
    return (
        <>
            <Head>
                <title>Runoff Risk Predictor</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <header className={styles.header}><h1>University of Delaware Great Lakes Runoff Risk Predictor</h1></header>
                <div className={styles.grid}>
                    <div className={styles.description}>
                        <Map latitude={43.1031} longitude={-84.7497} zoom={5}/>
                        {/* <NewMap ></NewMap> */}
                    </div>
                    
                    <div className={styles.description}>
                        {/* TODO: Slidebar */}
                      Hello World!</div>
                </div>
            </main>
        </>
    );
}
